travis:
  secure:
    BINSTAR_TOKEN: sBpfbWdx13nb5rPgYHC/Bsyt7lCXJVXpxbyYGnDCvL1d2aAs/vShcpXXbvUa02zfCVel6sFDHynbsJCWK2yAoZJr22w0XKeI0t2SqJXYtuLOTgGkxrcUgQDZio0oN74/C9xsDbEs5CVmNKzm+dz8/rY2+/p3XQ5NCueNoMQuKjIv4UKrZOXEX5/5QtYckc+kqXSQrC7Z5ry0y5lb5UUVC7G5AGfJD5vLGFfF1DdI7WWGJrVI5mIJjwSMGIOhLZdGkWCvKd2l61JOhBwo/5612LkEEy+ixoToKVWj4Ghr45AG4XZVuc9+BKDZX8/9HOtG18R7EVueGcO3cJCpJ5+bYVYQXcqtOWBo34IC++2qy4D9UakpHmGBsKhKNdkmvaUhP5Y9jFhl7Ua97ePQMSNCP9hqJXudXEaQwQfCvgWoFRFvPJVMl7A7W+436Jxxb1kfY7E+2Er9UHLAnVaQ102H3M7fMjvmxpQ82lLHJE5hoH1osk+kWeyTF0fy+BZz4aUubSP75F9kBY9Efai6hPexX7gP547a5RgXuT80bID3yYIo1HFQZZzl0/Y/cJHB10x7k0ScCTnSYaPt0l1bpeQkpFMcPUq94sA6S8aGB8CLIX3VzGjXPxixQh6xvoWEhvuC5Jg64uaQ+bBIOVfQ4cVxS44KQWw+nRGFb0thjEmBsp0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
