travis:
  secure:
    BINSTAR_TOKEN: puNXl4CjehXn/xD9dr3NWQuY9yfcIjy+9jJajLoF5xeC693ONc5O+LxIk++94vBadYHHxOCFu/gQ8Jrc7taEwgrIbS8jleE3CVZB4R7+EZpO5iZW1TcodY/UqcNDE/hLmo4X0evVxD3ktOJ0SuCA8XeA1Yvbo5A+oKKPflC0m1AJs/Ie4csiVWYk4TlETex8PnA7xmWWfM2zOphZEFqil1YRvFXUGTx7YgfKxEWcr6GB7vwP9NlPIdb2fi4Nb83dlTAnoxfI5eoOd1VhPAc7eHN5yvwbkNQwWcJQvRemxNuZ5KhGGxKBaOdWn2neOmGPR8126N70oYoiTCIqkUDlMYAuWMWr7GRKWdNghmvag/8vL4gD6DWiNP8zXTE8mqqFfup5Yrq03SDVKL5Npp56xi2mp4O/s9xD9SgHUGl8c2bCJ2ZKq/Jmn9JXuBd+VfJP2aznSEBFckVO0vUmzkc7hKCHpdLJoMJYzmY6ZZef6KMEFWSGyf1ceS0GFtFCwDwBvVFcphlm4sSbyK5QDgQEEqtG+bCcd8HXEicxN8Rbm8NzSR1b8NxMyEBZZD+6xOfc6OGBJCemTFPzr7BQkGg2e9R7vqHmkchrY9JzOctadQSJeX8hLrGoK4sIodl2jM8a3GVy2qPlULVKDp1iaW2Qd8psebpnp4G16KcRm46lItQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
